# 老化クラフト全体で関わる設定値
period: 100
init_age: 0
rejuvenate_age: 10
rejuvenate_item:
  - 'DRIED_KELP'

# 各世代別で異なる設定値
baby:
  walkspeed: 0.2
  maxhp: 20
  foodlevel: 20
  endword: 'ばぶ'
  useKanji: true
  checkHiragana: false
kids:
  walkspeed: 1.0
  maxhp: 20
  foodlevel: 20
  useKanji: true
  checkHiragana: false
young:
  walkspeed: 0.2
  maxhp: 20
  foodlevel: 20
  useKanji: true
  checkHiragana: false
adult:
  walkspeed: 0.2
  maxhp: 14
  foodlevel: 14
  useKanji: true
  checkHiragana: false
elderly:
  walkspeed: 0.1
  maxhp: 8
  foodlevel: 8
  caneat:
    - 'BEETROOT_SOUP'
    - 'MUSHROOM_STEW'
    - 'RABBIT_STEW'
    - 'SUSPICIOUS_STEW'
    - 'BREAD'
    - 'BAKED_POTATO'
  useKanji: false
  checkHiragana: true