name: Aging
version: ${project.version}
main: net.kunmc.lab.main.Aging
api-version: 1.16
authors: [ chanmo7na ]
description: 老化クラフト
commands:
  aging:
    description: Aging Main Command
    usage: /aging <start|stop|conf|restart|set|unset>
    permission: op
    permission-message: 権限がありません